import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {PersonSection} from '../components/personSection';


export default function Home({coaches, players}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fantasy League | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title}>Fantasy League <a href="https://nextjs.org"></a> LL</h1>
        <section>
          <p>Content is an example and will show up</p>
        </section>
        <PersonSection title="Coaches" people={coaches} />
        <PersonSection title="Players" people={players} />
    </div>
  )
}
export const getStaticProps = async ({ params }) => {
	const coaches = await fetch('http://node-api:8080/coach')
		.then(res => res.json())
		.catch(err => {console.log(err); return []});
  const players = await fetch('http://node-api:8080/player`')
		.then(res => res.json())
		.catch(err => {console.log(err); return []});
	return { props: { coaches, players } };
};