import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {PersonSection} from '../components/personSection';

export default function Home({players}) {
  return (
	<>
	<Head>
		<title>Fantasy League | Players</title>
		<meta name="description" content="Generated by create next app" />
		<link rel="icon" href="/favicon.ico" />
	</Head>
	<PersonSection title="Players" people={players} />
	</>
  )
}
export const getStaticProps = async ({ params }) => {
	const players = await fetch('http://node-api:8080/players')
		.then(res => res.json())
		.catch(err => {console.log(err); return []});
	return { props: { players } };
};