services:
  # react-app:
  #   image: node:lts-alpine
  #   restart: on-failure
  #   # depends_on:
  #   #   - api-server
  #   ports: ["8081:3000"]
  #   working_dir: /usr/node/app
  #   volumes:
  #     - ./src/app:/usr/node/app
  #     - /usr/node/app/node_modules
  #   command: "yarn start"
  #   ports:
  #     - ${HTTP_PORT:-8081}:80
  #     # - ${HTTPS_PORT:-8443}:443

#   node-api:
#     image: node:lts-alpine
#     depends_on:
#       - mongo-db
#     restart: "no"
#     expose: ["8082"]
#     volumes:
#       - ./src/api:/home/node/app:ro
#     command: "yarn dev"

# DATABASE LAYER
  mongo-db:
    image: mongo:focal # mongodb v5.x.x
    restart: always
    ports: ["12017:12017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin1234
    # volumes:
    #   - ./docker/mysql:/docker-entrypoint-initdb.d:ro

  db-viewer:
    image: mongo-express
    depends_on:
      - mongo-db
    restart: always
    ports: ["8084:8081"]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin1234
      ME_CONFIG_MONGODB_SERVER: mongo-db