services:
# Application Layer
  react-app:
    image: node:lts-alpine
    restart: on-failure
    networks:
      - frontend
    ports:
      - "8081:3000"
    working_dir: /home/node/app
    volumes:
      - ./src/app:/home/node/app:rw
      - /home/node/app/.next
    command: "yarn start"

  node-api:
    image: node:lts-alpine
    restart: "no"
    networks:
      - frontend
      - backend
    ports:
      - "8082:8080"
    user: node
    working_dir: /home/node/app
    volumes:
      - ./src/api:/home/node/app:rw
    command: "yarn start"

# DATABASE LAYER
  mysql-db:
    image: mysql:8-oracle
    restart: always
    networks:
      - backend
    ports:
      - "8086:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: final_project
    volumes:
      - ./src/mysql/init:/docker-entrypoint-initdb.d:ro

  db-viewer:
    image: adminer:4-standalone
    restart: always
    depends_on:
      - mysql-db
    networks:
      - backend
    ports:
      - "8084:8080"
networks:
  frontend:
  backend: